### ISSUE TITLE
enlarge_form does not runs

### ISSUE THREAD

**Issue by onduex** [ruifranco/odoo-addons#7]
Hi Sirs,
I'm testing your module enlarge_form in a V8 odoo installation over debian8, and it seems not to create inherited view you mention.
Any idea wellcom.
Thanks,

**Comment by ruifranco** [comment]
Hi!

That's an old module, now.
If it's causing problems, try this one, for instance:
https://www.odoo.com/apps/modules/8.0/web_sheet_full_width/

;)
